export const CONTACT = {
  phones: ['+919877865729', '+919872925078'],
  whatsapp: '+919877865729',
  email: 'himalayavalleyhomestead@gmail.com',
  address: {
    line1: 'Dharaman Utrala Road, Sornu',
    line2: 'Palampur, Himachal Pradesh – 176061',
    full: 'Dharaman Utrala Road, Sornu, Palampur, Himachal Pradesh – 176061',
  },
  googleMapsUrl: 'https://maps.google.com/?q=Dharaman+Utrala+Road+Sornu+Palampur+Himachal+Pradesh+176061',
  googleMapsEmbed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13512.952!2d76.5367!3d32.1109!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x391b479b6f23e2e5%3A0x9c8c0c0c0c0c0c0c!2sPalampur%2C%20Himachal%20Pradesh!5e0!3m2!1sen!2sin!4v1600000000000!5m2!1sen!2sin',
  social: {
    airbnb: 'https://www.airbnb.co.in/rooms/1398901259393587165',
    makemytrip: 'https://www.makemytrip.com',
    goibibo: 'https://www.goibibo.com',
  },
};

export const PROPERTY = {
  name: 'Himalayan Valley Homestead',
  tagline: 'A Serene Himalayan Homestead in Palampur',
  subtagline: 'Private Rooms · 2BHK · Entire Home',
  description: 'Surrounded by mountains, balconies, and open skies.',
  stats: {
    bedrooms: 5,
    bathrooms: 5,
    kitchens: 3,
    parking: 5,
  },
  locationHighlights: [
    'Approx. 7 km from Palampur town',
    'Scenic mountain surroundings',
    'Peaceful residential area',
  ],
  distanceFrom: {
    palampur: '7 km',
    dharamshala: '35 km',
    kangra: '38 km',
    pathankot: '110 km',
    chandigarh: '259 km',
    delhi: '483 km',
  },
};

export const TRUST_HIGHLIGHTS = [
  { title: 'Mountain & valley views', icon: 'Mountain' },
  { title: 'Rooftop terrace & verandas', icon: 'Home' },
  { title: 'Gated property with parking', icon: 'Car' },
  { title: 'Wi-Fi & power backup', icon: 'Wifi' },
  { title: 'Ideal for families & groups', icon: 'Users' },
];

export const STAY_OPTIONS = [
  {
    id: 'private-rooms',
    title: 'Private Rooms',
    shortTitle: 'Private Rooms',
    subtitle: 'Comfortable rooms with shared balconies and access to common areas.',
    description: 'Ideal for solo travelers, couples, or short getaways, our private rooms offer comfort, privacy, and access to shared balconies and common spaces.',
    features: [
      'Queen or double beds',
      'Clean shared bathrooms',
      'Wi-Fi access',
      'Common kitchen access',
      'Access to common living areas',
    ],
    idealFor: ['Solo travelers', 'Couples', 'Short getaways'],
    cta: 'View Full Details',
    ctaLink: '/stay-options/private-rooms',
    image: '/private-rooms/imgi_4_9066113e-9ca5-425a-a9fc-91fb5fda5db3.jpg',
  },
  {
    id: '2bhk',
    title: '2BHK Himalayan Homestay',
    shortTitle: '2BHK Homestay',
    subtitle: 'A private two-bedroom unit with kitchen, living space, and veranda.',
    description: 'Perfect for families or small groups, the 2BHK unit offers a private, self-contained stay with all the comforts of home.',
    features: [
      '2 bedrooms with attached bathrooms',
      'Private living area',
      'Fully equipped kitchen',
      'Large veranda & balcony access',
      'Dedicated workspace',
      'Ideal for longer stays',
    ],
    idealFor: ['Families', 'Small groups', 'Long stays', 'Remote work'],
    cta: 'View Full Details',
    ctaLink: '/stay-options/2bhk-homestay',
    image: '/2bhk-images/imgi_21_0b4742dd-5367-4583-acf2-8f46a517dbc3.jpg',
  },
  {
    id: 'entire-homestead',
    title: 'Whole Home Retreat',
    shortTitle: 'Entire Homestead',
    subtitle: 'Ideal for families or groups wanting privacy, space, and exclusivity.',
    description: 'For larger families, reunions, or group retreats, the entire homestead can be booked for exclusive use—offering maximum privacy and shared experiences.',
    features: [
      '5 bedrooms & 5 bathrooms',
      'Spacious living and dining areas',
      '3 fully equipped kitchens',
      'Rooftop terrace & verandas',
      'Gated property with parking for 5 cars',
    ],
    idealFor: ['Large families', 'Family reunions', 'Group retreats', 'Corporate offsites'],
    cta: 'View Full Details',
    ctaLink: '/stay-options/whole-home-retreat',
    image: '/image-5bhk/imgi_3_b36e7639-1e38-437c-98be-163dc9367a7f.jpg',
  },
];

export const AMENITIES = {
  essentials: {
    title: 'Essentials',
    items: [
      { name: 'Wi-Fi', icon: 'Wifi' },
      { name: 'Power backup', icon: 'Zap' },
      { name: '24/7 Hot Water', icon: 'Droplet', description: 'Solar-powered geysers' },
      { name: 'Clean linen & blankets', icon: 'Bed' },
      { name: 'Housekeeping support', icon: 'Sparkles' },
    ],
  },
  outdoors: {
    title: 'Outdoors & Views',
    items: [
      { name: 'Rooftop terrace', icon: 'Sun' },
      { name: 'Mountain-facing balconies', icon: 'Mountain' },
      { name: 'Veranda seating', icon: 'Armchair' },
    ],
  },
  parking: {
    title: 'Parking & Access',
    items: [
      { name: 'Gated property with CCTV', icon: 'Shield' },
      { name: 'On-site parking (5 cars)', icon: 'Car' },
    ],
  },
  addons: {
    title: 'Add-On Services',
    items: [
      { name: 'Airport transfers (on request)', icon: 'Plane' },
    ],
  },
};

export const DETAILED_AMENITIES = {
  bedroom: {
    title: 'Bedroom & Sleeping',
    icon: 'Bed',
    description: 'Comfortable sleeping arrangements with quality bedding and linens for a restful mountain stay.',
    items: [
      'Queen-size and double beds',
      'Premium quality mattresses',
      'Fresh cotton bed linens',
      'Warm blankets and quilts',
      'Extra pillows available',
      'Blackout curtains',
      'Ceiling fans',
      'Wardrobes and storage space',
      'Bedside tables with lamps',
      'Extra mattresses available (Rs. 500/night)',
    ],
  },
  bathroom: {
    title: 'Bathroom & Toiletries',
    icon: 'Bath',
    description: 'Clean, well-maintained bathrooms with hot water available round the clock.',
    items: [
      '24/7 hot water (solar geysers)',
      'Western-style toilets',
      'Hot and cold water supply',
      'Clean towels provided',
      'Basic toiletries (soap, shampoo)',
      'Hair dryer available on request',
      'Attached bathrooms in 2BHK',
      'Shared bathrooms for private rooms',
      'Regular housekeeping',
      'First-floor powder room',
    ],
  },
  kitchen: {
    title: 'Kitchen & Dining',
    icon: 'UtensilsCrossed',
    description: 'Fully equipped kitchens for self-catering with all essential appliances and utensils.',
    items: [
      '3 fully equipped kitchens',
      'Gas stove with cylinder',
      'Refrigerator',
      'Microwave oven',
      'Electric kettle',
      'Water purifier (RO)',
      'Complete cooking utensils',
      'Plates, cups, and cutlery',
      'Dining table with seating',
      'Basic spices and condiments',
      'Tea and coffee making facilities',
      'Pressure cooker and kadhai',
    ],
  },
  livingSpaces: {
    title: 'Living & Common Areas',
    icon: 'Sofa',
    description: 'Spacious living areas designed for relaxation and quality time with family and friends.',
    items: [
      'Large living room',
      'Comfortable seating arrangements',
      'Multiple veranda spaces',
      'Indoor dining area',
      'Reading corners',
      'Board games available',
      'Bookshelves with reading material',
      'Common gathering spaces',
      'Shoe rack at entrance',
      'Coat hooks and storage',
    ],
  },
  workspace: {
    title: 'Work From Mountains',
    icon: 'Laptop',
    description: 'Reliable connectivity and comfortable workspaces for remote workers and digital nomads.',
    items: [
      'High-speed Wi-Fi throughout',
      'Dedicated work desk areas',
      'Comfortable seating for work',
      'Multiple charging points',
      'Good natural lighting',
      'Quiet environment for calls',
      'Balcony workspaces',
      'Mobile network coverage',
      'Power backup for uninterrupted work',
      'Long-stay discounts available',
    ],
  },
  outdoors: {
    title: 'Outdoor Spaces & Views',
    icon: 'Mountain',
    description: 'Expansive outdoor areas with stunning Himalayan views and fresh mountain air.',
    items: [
      'Rooftop terrace with 360° views',
      'Multiple balconies with mountain views',
      'Spacious verandas with seating',
      'Garden seating areas',
      'Dhauladhar mountain range views',
      'Valley and tea garden vistas',
      'Sunrise and sunset viewing spots',
      'Star gazing from terrace',
      'Surrounded by greenery',
      'Fresh mountain air',
    ],
  },
  safety: {
    title: 'Safety & Security',
    icon: 'Shield',
    description: 'A secure, gated property with safety measures for peace of mind during your stay.',
    items: [
      'Gated property with secure access',
      '8 CCTV cameras for 24/7 surveillance',
      'On-site caretaker',
      'Fire extinguishers',
      'First aid kit',
      'Emergency contact numbers',
      'Well-lit pathways',
      'Smoke-free indoor policy',
      'Carbon monoxide detector',
      'Secure parking area',
      'Local emergency services nearby',
    ],
  },
  parking: {
    title: 'Parking & Transportation',
    icon: 'Car',
    description: 'Ample parking space and transportation assistance for hassle-free access.',
    items: [
      'Free on-site parking for 5 cars',
      'Covered parking available',
      'Easy road access',
      'Airport/station transfers (on request)',
      'Local taxi arrangements',
      'Directions and navigation support',
      'Vehicle-friendly approach road',
      'Two-wheeler parking',
      'Self-drive friendly location',
      'Driver accommodation if needed',
    ],
  },
  entertainment: {
    title: 'Entertainment & Leisure',
    icon: 'Music',
    description: 'Options for entertainment and relaxation during your mountain getaway.',
    items: [
      'Bluetooth speakers',
      'Board games and cards',
      'Books and magazines',
      'Photography spots',
      'Bird watching opportunities',
      'Nature walks from property',
      'Bonfire on demand (Rs. 200)',
      'Local guide recommendations',
      'Trekking route information',
      'Cultural experience suggestions',
    ],
  },
  climate: {
    title: 'Heating & Climate',
    icon: 'Flame',
    description: 'Stay comfortable in all seasons with heating options and proper ventilation.',
    items: [
      'Electric heater on demand (Rs. 200/day)',
      'Extra blankets and quilts',
      'Hot water bottles available',
      'Ceiling fans (summer)',
      'Cross ventilation design',
      'Natural cooling in summer',
      'Fireplace in common area',
      'Warm interiors',
      'Pleasant climate year-round',
      'Cool mountain breeze',
    ],
  },
  services: {
    title: 'Additional Services',
    icon: 'Concierge',
    description: 'Extra services available on request to enhance your stay experience.',
    items: [
      'Daily housekeeping',
      'Laundry service (on request)',
      'Local cook arrangements',
      'Grocery delivery assistance',
      'Local tour arrangements',
      'Paragliding booking help',
      'Temple visit coordination',
      'Picnic arrangements',
      'Birthday/anniversary setups',
      'Extended stay packages',
    ],
  },
};

export const NEARBY_ATTRACTIONS = [
  {
    name: 'Palampur Tea Gardens',
    description: 'Famous tea estates with scenic walks and factory tours.',
    distance: '8 km',
    image: '/palampur-tea-plantation.webp',
  },
  {
    name: 'Chamunda Devi Temple',
    description: 'Ancient temple dedicated to Goddess Chamunda.',
    distance: '15 km',
    image: '/chamunda-devi.webp',
  },
  {
    name: 'Sobha Singh Art Gallery',
    description: 'Gallery showcasing works of renowned artist Sobha Singh.',
    distance: '12 km',
    image: '/shobha-singh-art-gallery.jpg',
  },
  {
    name: 'Baijnath Shiva Temple',
    description: 'Historic 13th-century temple with stunning architecture.',
    distance: '16 km',
    image: '/baijnath-temple-palampur.jpg',
  },
  {
    name: 'Bir Billing',
    description: 'World-famous paragliding destination and Tibetan settlement.',
    distance: '35 km',
    image: '/bir-billing.jpg',
  },
  {
    name: 'Tulip Garden, Palampur',
    description: 'Vibrant tulip fields with colorful blooms during spring season.',
    distance: '6 km',
    image: '/tulip-garden.jpeg',
  },
];

export const SLOW_EXPERIENCES = [
  {
    title: 'Morning tea on the terrace',
    description: 'Start your day with chai and panoramic Himalayan views.',
    icon: 'Coffee',
  },
  {
    title: 'Work-from-the-hills stays',
    description: 'Reliable Wi-Fi and peaceful workspace for remote work.',
    icon: 'Laptop',
  },
  {
    title: 'Stargazing & quiet evenings',
    description: 'Clear mountain skies perfect for stargazing.',
    icon: 'Star',
  },
  {
    title: 'Family time in shared spaces',
    description: 'Spacious common areas for quality family moments.',
    icon: 'Heart',
  },
];

export const GALLERY_IMAGES = [
  { src: '/hhs-hero1.jpg', category: 'Exteriors', alt: 'Homestead exterior with mountain backdrop' },
  { src: '/hhs-hero2.jpg', category: 'Exteriors', alt: 'Homestead building view' },
  { src: '/hhs-hero3.jpeg', category: 'Exteriors', alt: 'Homestead exterior at dusk' },
  { src: '/hhs-hero4.avif', category: 'Exteriors', alt: 'Homestead panoramic view' },
  { src: '/hhs-hero-5.jpg', category: 'Rooftop & Views', alt: 'Views from the rooftop terrace' },
  { src: '/hhs-hero-6.jpg', category: 'Exteriors', alt: 'Homestead full exterior view' },
  { src: '/entrance-road.jpg', category: 'Exteriors', alt: 'Entrance road to the homestead' },
  { src: '/outdoor-view.jpeg', category: 'Rooftop & Views', alt: 'Mountain views from the property' },
  { src: '/room-hhs.avif', category: 'Rooms', alt: 'Cozy bedroom with mountain views' },
  { src: '/hote-essentials.jpg', category: 'Rooms', alt: 'Room essentials and amenities' },
  { src: '/life-at-homestead.jpg', category: 'Common Areas', alt: 'Life at the homestead' },
  { src: '/morningtea.jpg', category: 'Common Areas', alt: 'Morning tea on the terrace' },
  { src: '/amenties-banner.jpg', category: 'Common Areas', alt: 'Homestead amenities' },
  { src: '/work-from-mountains.png', category: 'Common Areas', alt: 'Work from mountains setup' },
  { src: '/hhs-banner-about.jpg', category: 'Rooftop & Views', alt: 'Scenic view from the homestead' },
  { src: '/palampur-location.jpg', category: 'Surroundings', alt: 'Palampur valley location' },
  { src: '/palampur-tea-plantation.webp', category: 'Surroundings', alt: 'Tea gardens near Palampur' },
  { src: '/bir-billing.jpg', category: 'Surroundings', alt: 'Bir Billing paragliding destination' },
  { src: '/baijnath-temple-palampur.jpg', category: 'Surroundings', alt: 'Baijnath Shiva Temple' },
  { src: '/chamunda-devi.webp', category: 'Surroundings', alt: 'Chamunda Devi Temple' },
  { src: '/shobha-singh-art-gallery.jpg', category: 'Surroundings', alt: 'Sobha Singh Art Gallery' },
  { src: '/private-rooms/imgi_4_9066113e-9ca5-425a-a9fc-91fb5fda5db3.jpg', category: 'Private Rooms', alt: 'Private Room interior' },
  { src: '/private-rooms/imgi_5_6640bf7c-0d32-4aaa-8778-eb2bf3471216.jpg', category: 'Private Rooms', alt: 'Private Room view' },
  { src: '/private-rooms/imgi_10_6daca774-6a97-40e9-8226-c735cbf18b39.jpg', category: 'Private Rooms', alt: 'Private Room bedroom' },
  { src: '/private-rooms/imgi_11_c6b2e6cd-c9cc-445c-a766-70486f11b376.jpg', category: 'Private Rooms', alt: 'Private Room details' },
  { src: '/private-rooms/imgi_12_0f2bd7a3-a1f9-4b64-ae57-776ccfbf5f7d.jpg', category: 'Private Rooms', alt: 'Private Room amenities' },
  { src: '/private-rooms/imgi_77_75eb1d02-5b52-4544-a7b4-63fb3dbd276b.jpg', category: 'Private Rooms', alt: 'Private Room space' },
  { src: '/private-rooms/imgi_78_b3edf462-afbf-4792-a24e-4cb142af0986.jpg', category: 'Private Rooms', alt: 'Private Room comfort' },
  { src: '/private-rooms/imgi_79_cf489d01-914a-48f4-8c43-e4d78990eb4a.jpg', category: 'Private Rooms', alt: 'Private Room furnishings' },
  { src: '/private-rooms/imgi_80_2e97d25f-73e2-4852-bd2e-9980bddf6538.jpg', category: 'Private Rooms', alt: 'Private Room decor' },
  { src: '/private-rooms/imgi_81_14c2f2b8-8025-42ed-b7d3-18b91cee370d.jpg', category: 'Private Rooms', alt: 'Private Room window view' },
  { src: '/private-rooms/imgi_82_253766ef-fdcc-4fec-af13-112f0018dc10.jpg', category: 'Private Rooms', alt: 'Private Room setting' },
  { src: '/private-rooms/imgi_83_b396f6a4-37c6-4073-977d-72074c917456.jpg', category: 'Private Rooms', alt: 'Private Room atmosphere' },
  { src: '/private-rooms/imgi_84_96c66bcb-e12b-42d5-a8c7-5106f3c6569e.jpg', category: 'Private Rooms', alt: 'Private Room layout' },
  { src: '/2bhk-images/imgi_21_0b4742dd-5367-4583-acf2-8f46a517dbc3.jpg', category: '2BHK', alt: '2BHK living space' },
  { src: '/2bhk-images/imgi_33_43fbfb3e-3d71-4e38-abea-be7e5f0981f8.jpg', category: '2BHK', alt: '2BHK interior' },
  { src: '/2bhk-images/imgi_34_89bf479b-b6b7-4d65-97ce-8a97d444958c.jpg', category: '2BHK', alt: '2BHK bedroom' },
  { src: '/2bhk-images/imgi_104_a4e35648-00d6-43f8-a46e-e45a63a5d4cb.jpg', category: '2BHK', alt: '2BHK kitchen' },
  { src: '/2bhk-images/imgi_105_ca220948-3a78-4c5a-96f1-3cbd5ab5e277.jpg', category: '2BHK', alt: '2BHK dining area' },
  { src: '/2bhk-images/imgi_106_52aacf1d-17b9-4918-ab06-f8fcb74cc912.jpg', category: '2BHK', alt: '2BHK amenities' },
  { src: '/2bhk-images/imgi_107_bef4ba2f-041d-4c9a-856e-04e4a2f92f02.jpg', category: '2BHK', alt: '2BHK balcony' },
  { src: '/2bhk-images/imgi_108_5e8455ea-aec1-49cf-b0e7-dc13d898d8ec.jpg', category: '2BHK', alt: '2BHK veranda' },
  { src: '/2bhk-images/imgi_109_ce0e06fa-0722-4582-b027-f061d55ed0c8.jpg', category: '2BHK', alt: '2BHK details' },
  { src: '/2bhk-images/imgi_121_f304b583-a0d3-43c3-a096-6b6967c4abfd.jpg', category: '2BHK', alt: '2BHK furnishings' },
  { src: '/2bhk-images/imgi_122_b92eb6cb-2906-4f49-8056-a77144a117ec.jpg', category: '2BHK', alt: '2BHK comfort' },
  { src: '/2bhk-images/imgi_123_64cb630f-ac96-41c5-aa62-859268a26423.jpg', category: '2BHK', alt: '2BHK decor' },
  { src: '/2bhk-images/imgi_124_68f02d57-1a69-4bab-9178-ece1e5d4dce9.jpg', category: '2BHK', alt: '2BHK space' },
  { src: '/2bhk-images/imgi_125_c5bda4c5-4452-4481-b74e-f9303172d18a.jpg', category: '2BHK', alt: '2BHK setting' },
  { src: '/2bhk-images/imgi_127_153338f2-882c-4d0e-a89c-666e9d94c067.jpg', category: '2BHK', alt: '2BHK atmosphere' },
  { src: '/2bhk-images/imgi_128_1a147d2e-ce77-4881-b6e7-d2dd74f50b39.jpg', category: '2BHK', alt: '2BHK layout' },
  { src: '/hhs-2bhk.jpeg', category: '2BHK', alt: '2BHK unit overview' },
  { src: '/image-5bhk/imgi_3_b36e7639-1e38-437c-98be-163dc9367a7f.jpg', category: 'Whole Home', alt: 'Whole Home exterior' },
  { src: '/image-5bhk/imgi_88_a2880a0a-4487-4039-b15b-1e158f096168.jpg', category: 'Whole Home', alt: 'Whole Home living room' },
  { src: '/image-5bhk/imgi_90_6c72cd52-3d08-4b69-a9b1-558e50875c46.jpg', category: 'Whole Home', alt: 'Whole Home bedroom 1' },
  { src: '/image-5bhk/imgi_91_7b0142cb-2ecd-4207-a906-039fbd1f81fa.jpg', category: 'Whole Home', alt: 'Whole Home bedroom 2' },
  { src: '/image-5bhk/imgi_92_a3b672cb-8011-41e1-9554-7b4a80836df3.jpg', category: 'Whole Home', alt: 'Whole Home bedroom 3' },
  { src: '/image-5bhk/imgi_93_b373ffa0-01f3-4f1e-abdb-abeb7d31016d.jpg', category: 'Whole Home', alt: 'Whole Home bedroom 4' },
  { src: '/image-5bhk/imgi_94_5b6c05bb-4f42-48ee-a314-85e741a5748c.jpg', category: 'Whole Home', alt: 'Whole Home bedroom 5' },
  { src: '/image-5bhk/imgi_95_f09bdcf7-22dc-4d45-b5ad-3330ab61e753.jpg', category: 'Whole Home', alt: 'Whole Home kitchen' },
  { src: '/image-5bhk/imgi_108_fe220c79-996d-433d-8adb-aa6efe23c9d6.jpg', category: 'Whole Home', alt: 'Whole Home dining' },
  { src: '/image-5bhk/imgi_109_09f011a7-8fe3-4d11-9f5d-4b1fc0a97443.jpg', category: 'Whole Home', alt: 'Whole Home bathroom' },
  { src: '/image-5bhk/imgi_110_98479872-7443-4b86-a504-1f852a79c906.jpg', category: 'Whole Home', alt: 'Whole Home balcony' },
  { src: '/image-5bhk/imgi_111_af671f23-78a6-4cdd-9e06-8326f653715f.jpg', category: 'Whole Home', alt: 'Whole Home terrace' },
  { src: '/image-5bhk/imgi_112_62c2ccc9-4da9-457a-b912-59e67cca7394.jpg', category: 'Whole Home', alt: 'Whole Home details' },
  { src: '/image-5bhk/imgi_113_b7976339-9eb1-4a37-9fb8-bd34a5f70a08.jpg', category: 'Whole Home', alt: 'Whole Home furnishings' },
  { src: '/image-5bhk/imgi_114_455a0e93-0834-4d7e-978a-83e898564a23.jpg', category: 'Whole Home', alt: 'Whole Home decor' },
  { src: '/image-5bhk/imgi_115_a5b96a87-f3f5-42bb-967c-2dcaf5eb481c.jpg', category: 'Whole Home', alt: 'Whole Home amenities' },
  { src: '/image-5bhk/imgi_116_526f12ad-0e94-4972-95b0-bad29968c9bf.jpg', category: 'Whole Home', alt: 'Whole Home comfort' },
  { src: '/image-5bhk/imgi_117_1440f636-d0f3-4b99-9ed6-2001041823b0.jpg', category: 'Whole Home', alt: 'Whole Home space' },
  { src: '/image-5bhk/imgi_118_f65a1908-41e6-4a81-b47d-eb910f09e48a.jpg', category: 'Whole Home', alt: 'Whole Home views' },
  { src: '/image-5bhk/imgi_119_025349c7-cd22-44ec-897a-5f61592cd1bd.jpg', category: 'Whole Home', alt: 'Whole Home setting' },
  { src: '/image-5bhk/imgi_120_0b0eba79-b4ad-4137-b8cb-7746d6d60c11.jpg', category: 'Whole Home', alt: 'Whole Home atmosphere' },
  { src: '/image-5bhk/imgi_121_c770f0d5-d0be-43b0-a858-cf97fb921894.jpg', category: 'Whole Home', alt: 'Whole Home interior' },
  { src: '/image-5bhk/imgi_122_c90ce630-5f8a-444e-874e-32c9153c517a.jpg', category: 'Whole Home', alt: 'Whole Home layout' },
  { src: '/image-5bhk/imgi_123_587c7f6d-ecff-4f01-985d-c1dd6cd9913b.jpg', category: 'Whole Home', alt: 'Whole Home entrance' },
  { src: '/image-5bhk/imgi_124_5e02026b-8e74-42ae-988f-9153f57ffa22.jpg', category: 'Whole Home', alt: 'Whole Home garden' },
  { src: '/image-5bhk/imgi_125_040255c8-2726-4aec-92d8-3015e3b416c2.jpg', category: 'Whole Home', alt: 'Whole Home outdoor' },
  { src: '/image-5bhk/imgi_126_ad8267e7-d719-4721-9294-6696756758f5.jpg', category: 'Whole Home', alt: 'Whole Home patio' },
  { src: '/image-5bhk/imgi_127_f5449b36-f33d-4a88-ac77-86b68fee3f44.jpg', category: 'Whole Home', alt: 'Whole Home veranda' },
  { src: '/image-5bhk/imgi_128_7858e3ac-ca03-447a-b042-8ff194f198b0.jpg', category: 'Whole Home', alt: 'Whole Home common area' },
  { src: '/image-5bhk/imgi_129_e9cb99ac-d45d-4db6-9261-3f6ab1eee029.jpg', category: 'Whole Home', alt: 'Whole Home sitting area' },
  { src: '/image-5bhk/imgi_130_6eaed2f9-f63f-46fb-bb5a-cabd361e1ebd.jpg', category: 'Whole Home', alt: 'Whole Home lounge' },
  { src: '/image-5bhk/imgi_131_4efa5879-8520-4d0a-8bd8-9a0bcc95a7a6.jpg', category: 'Whole Home', alt: 'Whole Home evening view' },
  { src: '/image-5bhk/imgi_132_975cae83-ee4f-4b4c-985e-2e7999de6ff7.jpg', category: 'Whole Home', alt: 'Whole Home panorama' },
  { src: '/guest-moments/whatsapp_image_2026-01-11_at_12.11.37.jpeg', category: 'Guest Moments', alt: 'Family gathering at the homestead' },
  { src: '/guest-moments/whatsapp_image_2026-01-11_at_12.11.14.jpeg', category: 'Guest Moments', alt: 'Memorable moments together' },
  { src: '/guest-moments/whatsapp_image_2026-01-11_at_12.10.25.jpeg', category: 'Guest Moments', alt: 'Creating memories at the homestead' },
  { src: '/guest-moments/whatsapp_image_2026-01-11_at_12.10.12.jpeg', category: 'Guest Moments', alt: 'Cherished moments with loved ones' },
  { src: '/amenities/kitchen.jpg', category: 'Common Areas', alt: 'Fully equipped kitchen' },
  { src: '/amenities/bathroom-ntoiletries.jpg', category: 'Rooms', alt: 'Bathroom with toiletries' },
  { src: '/amenities/living-n-common-areas.jpg', category: 'Common Areas', alt: 'Living and common areas' },
  { src: '/quiet-evenings.jpeg', category: 'Rooftop & Views', alt: 'Quiet evenings with mountain views' },
];

export const POLICIES = [
  {
    title: 'Check-in Time',
    content: 'Check-in time is 11:00 AM. Early check-in may be available on request, subject to availability.',
  },
  {
    title: 'Check-out Time',
    content: 'Check-out time is 2:00 PM. Late check-out may be available on request, subject to availability.',
  },
  {
    title: 'Identification',
    content: 'Valid government-issued ID is required for all guests at the time of check-in. This includes Aadhaar Card, Passport, Driving License, or Voter ID.',
  },
  {
    title: 'Age Requirement',
    content: 'The primary guest making the booking must be 18 years of age or older.',
  },
  {
    title: 'Pet Policy',
    content: 'Pets are not allowed at the homestead.',
  },
  {
    title: 'Quiet Hours',
    content: 'As the property is located in a peaceful residential setting, we request guests to respect quiet hours, especially during late evenings and early mornings.',
  },
  {
    title: 'Smoking',
    content: 'Smoking is not allowed inside the rooms. Smoking is permitted only on the terrace.',
  },
  {
    title: 'Cancellation',
    content: 'Cancellation policies vary based on the booking platform used. For direct bookings, please contact us for our cancellation terms.',
  },
  {
    title: 'Extra Mattresses',
    content: 'Extra mattresses are available at an additional charge of Rs. 500 per mattress per night.',
  },
];

export const DETAILED_POLICIES = {
  checkInOut: {
    title: 'Check-in & Check-out',
    icon: 'Clock',
    items: [
      { label: 'Check-in Time', value: '11:00 AM onwards' },
      { label: 'Check-out Time', value: '2:00 PM' },
      { label: 'Early Check-in', value: 'Available on request (subject to availability)' },
      { label: 'Late Check-out', value: 'Available on request (additional charges may apply)' },
      { label: 'Self Check-in', value: 'Available with prior arrangement' },
    ],
    note: 'Please inform us of your expected arrival time so we can ensure a smooth check-in experience.',
  },
  identification: {
    title: 'Guest Identification',
    icon: 'FileCheck',
    items: [
      { label: 'Required Documents', value: 'Valid government-issued photo ID for all adult guests' },
      { label: 'Accepted IDs (Indian)', value: 'Aadhaar Card, Passport, Driving License, Voter ID' },
      { label: 'Foreign Nationals', value: 'Valid Passport and Visa required' },
      { label: 'Registration', value: 'Guest register to be filled as per local regulations' },
      { label: 'Age Requirement', value: 'Primary guest must be 18 years or older' },
    ],
    note: 'ID verification is mandatory as per local government regulations for all homestays in Himachal Pradesh.',
  },
  houseRules: {
    title: 'House Rules',
    icon: 'Home',
    items: [
      { label: 'Quiet Hours', value: '10:00 PM to 7:00 AM' },
      { label: 'Maximum Guests', value: 'As per booking confirmation only' },
      { label: 'Visitors', value: 'Not allowed without prior approval' },
      { label: 'Parties/Events', value: 'Not permitted without prior arrangement' },
      { label: 'Common Areas', value: 'Shared with respect for other guests' },
    ],
    note: 'We are located in a peaceful residential area. Please be mindful of neighbors and fellow guests.',
  },
  smoking: {
    title: 'Smoking & Alcohol Policy',
    icon: 'Ban',
    items: [
      { label: 'Indoor Smoking', value: 'Strictly prohibited in all rooms' },
      { label: 'Designated Area', value: 'Terrace only (please dispose butts responsibly)' },
      { label: 'Alcohol', value: 'Permitted for personal consumption only' },
      { label: 'Illegal Substances', value: 'Strictly prohibited (zero tolerance)' },
      { label: 'Violation', value: 'May result in immediate checkout without refund' },
    ],
    note: 'Any smell of smoke inside rooms may result in additional cleaning charges.',
  },
  pets: {
    title: 'Pet Policy',
    icon: 'PawPrint',
    items: [
      { label: 'Pets Allowed', value: 'No, pets are not permitted' },
      { label: 'Service Animals', value: 'Please contact us in advance to discuss' },
      { label: 'Local Wildlife', value: 'Please do not feed or disturb' },
    ],
    note: 'We understand pets are family. Unfortunately, due to our property setup and local conditions, we cannot accommodate pets at this time.',
  },
  payment: {
    title: 'Payment & Pricing',
    icon: 'CreditCard',
    items: [
      { label: 'Booking Confirmation', value: 'Advance payment required' },
      { label: 'Payment Methods', value: 'UPI, Bank Transfer, or via booking platforms' },
      { label: 'Extra Mattress', value: 'Rs. 500 per mattress per night' },
      { label: 'Electric Heater', value: 'Rs. 200 per day (on demand)' },
      { label: 'Bonfire', value: 'Rs. 200 (on demand)' },
      { label: 'Airport Transfers', value: 'Available at additional cost' },
      { label: 'Long Stay Discount', value: 'Available for stays of 7+ nights' },
    ],
    note: 'Prices may vary by season and booking platform. Contact us directly for best rates.',
  },
  cancellation: {
    title: 'Cancellation & Refunds',
    icon: 'CalendarX',
    items: [
      { label: 'Free Cancellation', value: 'Up to 7 days before check-in (full refund)' },
      { label: '3-7 Days Notice', value: '50% refund of booking amount' },
      { label: 'Less than 3 Days', value: 'No refund applicable' },
      { label: 'No-Show', value: 'No refund' },
      { label: 'Platform Bookings', value: 'Subject to respective platform policies' },
    ],
    note: 'For exceptional circumstances, please contact us directly. We try to be understanding of genuine situations.',
  },
  damage: {
    title: 'Property & Damage Policy',
    icon: 'AlertTriangle',
    items: [
      { label: 'Care of Property', value: 'Please treat the homestead as your own home' },
      { label: 'Damage Reporting', value: 'Report any damage immediately to hosts' },
      { label: 'Accidental Damage', value: 'Guest responsible for repair/replacement costs' },
      { label: 'Intentional Damage', value: 'Full cost recovery plus additional charges' },
      { label: 'Missing Items', value: 'Will be charged at replacement value' },
    ],
    note: 'We trust our guests to respect the property. Minor accidents happen and we understand.',
  },
  safety: {
    title: 'Safety & Security',
    icon: 'Shield',
    items: [
      { label: 'Gated Property', value: 'Secure access with on-site caretaker' },
      { label: 'CCTV Surveillance', value: '8 cameras installed for 24/7 monitoring' },
      { label: 'Fire Safety', value: 'Extinguishers and smoke detectors installed' },
      { label: 'First Aid', value: 'Basic first aid kit available' },
      { label: 'Emergency', value: 'Local hospital within 15 km' },
      { label: 'Valuables', value: 'Guests responsible for personal belongings' },
    ],
    note: 'Emergency contact numbers and local hospital information provided at check-in.',
  },
  children: {
    title: 'Children & Family Policy',
    icon: 'Baby',
    items: [
      { label: 'Children Welcome', value: 'Yes, families with children are welcome' },
      { label: 'Child Safety', value: 'Parents responsible for supervision' },
      { label: 'Balconies/Terrace', value: 'Please supervise children at all times' },
      { label: 'Baby Cot', value: 'Not available (bring your own if needed)' },
      { label: 'High Chair', value: 'Not available' },
    ],
    note: 'The property has stairs and open balconies. Please ensure children are supervised.',
  },
  kitchen: {
    title: 'Kitchen Usage',
    icon: 'ChefHat',
    items: [
      { label: 'Self-Catering', value: 'Fully equipped kitchens available' },
      { label: 'Utensils', value: 'Basic cooking equipment provided' },
      { label: 'Gas Cylinder', value: 'Refills available (charges apply)' },
      { label: 'Cleanliness', value: 'Please clean after use' },
      { label: 'Groceries', value: 'Guests to arrange (local shops 2 km away)' },
    ],
    note: 'Local cook can be arranged on request for an additional fee.',
  },
  environment: {
    title: 'Environmental Responsibility',
    icon: 'Leaf',
    items: [
      { label: 'Waste Segregation', value: 'Please separate dry and wet waste' },
      { label: 'Water Conservation', value: 'We request mindful usage' },
      { label: 'Electricity', value: 'Please switch off when not in use' },
      { label: 'No Littering', value: 'Please use designated bins' },
      { label: 'Nature Respect', value: 'Do not disturb plants or wildlife' },
    ],
    note: 'We are committed to sustainable tourism. Your support in keeping our mountains clean is appreciated.',
  },
};

export const NAV_LINKS = [
  { name: 'Home', path: '/' },
  { name: 'About', path: '/about' },
  { name: 'Stay Options', path: '/stay-options' },
  { name: 'Amenities', path: '/amenities' },
  { name: 'Homemade Food', path: '/homemade-food' },
  { name: 'Experiences', path: '/experiences' },
  { name: 'Gallery', path: '/gallery' },
  { name: 'Location', path: '/location' },
  { name: 'Testimonials', path: '/testimonials' },
  { name: 'Policies', path: '/policies' },
  { name: 'Contact', path: '/contact' },
];
